MeuPrimeiroProjeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

polls/models.py
import datetime 
from django.db import models
from django.utils import timezone
from django.contrib import admin 

class Question(models.Model):    
    question_text = models.CharField('Questão',max_length=200)
    pub_date = models.DateTimeField('Data Publicada')
    nivel = (
        ('F','Fácil'),
        ('M','Médio'),
        ('D','Difícil'),
        ('E','Expert'),
    )
    dificuldade = models.CharField(max_length=1, choices=nivel, default='F')
     
#     @admin.display(
#         boolean=True,
#         ordering=['pub_date'],
#         description='Publicada recentemente?', 
#         )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
 
    def __str__(self) :
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) :
        return self.choice_text

polls/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, response
from django.urls import reverse
from .models import Choice, Question
from django.views import generic 

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        was_published_recently() returns False for questions whose pub_date
        is in the future.
        """    
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'question':question,
            'error_message': "Você não selecionou uma opção."
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return response.HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}
<link href="{% static 'polls/style.css' %}" rel="stylesheet" type="text/css"/>
<body>
    <div class='principal'>
        <form action="{% url 'polls:vote' question.id %}" method="POST">
            {% csrf_token %}        
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
        
                {% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
        
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />       
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text}}</label> 
                    <br />
                {% endfor %}
            </fieldset>
            <input type="submit" value="Votar" /> 
            <a href="{% url 'polls:index' %}">Início</a>            
        </form>
    </div>
</body>

polls/templates/polls/index.html
{% load static %}
<link href="{% static 'polls/style.css' %}" rel="stylesheet" type="text/css"/>
<body>
    <div class='principal'>
        {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                    <li>
                        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} - Dificulade {{ question.get_dificuldade_display }}</a> 
                    </li>
                {% endfor %}    
            </ul>
        {% else %}
            <p>Sem artigos disponíveis.</p>
        {% endif %}
    </div>
</body>

polls/templates/polls/results.html
{% load static %}
<link href="{% static 'polls/style.css' %}" rel="stylesheet" type="text/css"/>
<body>
    <div class='principal'>
        <h1>{{ question.question_text }}</h1>

        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}  {{ choice.votes }} voto{{ choice.votes|pluralize }}</li>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:detail' question.id %}">Votar novamente?</a>
    </div>
</body>